Document: libmpsse
Title: Debian libmpsse Manual
Author: <insert document author here>
Abstract: This manual describes what libmpsse is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libmpsse/libmpsse.sgml.gz

Format: postscript
Files: /usr/share/doc/libmpsse/libmpsse.ps.gz

Format: text
Files: /usr/share/doc/libmpsse/libmpsse.text.gz

Format: HTML
Index: /usr/share/doc/libmpsse/html/index.html
Files: /usr/share/doc/libmpsse/html/*.html
